# Generate synthetic data

In [ ]:
#Import python libraries
import pandas as pd
import numpy as np
from random import randint, choice, seed
from datetime import datetime, timedelta

In [ ]:
# Set seed

np.random.seed(12)
seed(12)

Creating data for table #2 | **Subscriptions**

In [ ]:
# Number of customers
n_customers = 100

In [ ]:
from numpy.random import random
subscription_records = []
sub_id = 1

end_of_analysis = datetime(2025, 12, 1)

# Generate the subscription history for every user
for c_id in range (1, n_customers + 1):

  #Every user beging his subscription on a random month (Jan-June) in 2025
  start_month = randint(1, 6)
  current_date = datetime(2025, start_month, 1)

  # Simulating if the customer will churn
  will_churn = choice([True, False])

  if will_churn:
    months_active = randint(1, 6)
  else:
    months_active = 12

  for month in range(months_active):

    if current_date > end_of_analysis:
      break

    if will_churn and month == months_active -1:
      status = 'Churned'
    else:
      status = 'Active'

    subscription_records.append({
        'subscription_id': sub_id,
        'customer_id': c_id,
        'payment_date': current_date,
        'status': status
    })

    sub_id += 1

    if status == "Churned":
      break

    current_date = (current_date + timedelta(days=32)).replace(day=1)

df_subscriptions = pd.DataFrame(subscription_records)

In [ ]:
df_subscriptions.head(10)

   subscription_id  customer_id payment_date  status
0                1            1   2025-04-01  Active
1                2            1   2025-05-01  Active
2                3            1   2025-06-01  Active
3                4            1   2025-07-01  Active
4                5            1   2025-08-01  Active
5                6            1   2025-09-01  Active
6                7            1   2025-10-01  Active
7                8            1   2025-11-01  Active
8                9            1   2025-12-01  Active
9               10            2   2025-06-01  Active

In [ ]:
# Save the subscriptions DataFrame

df_subscriptions.to_csv('subscriptions_data.csv', index = False)

Creating data for Table #1 | **Users table**

In [ ]:
#Signup date
df_signup_dates= df_subscriptions.groupby('customer_id')['payment_date'].min().reset_index()
df_signup_dates.columns = ['customer_id', 'signup_date']

In [ ]:
#Country
countries = ['Poland', 'Germany', 'Austria', 'Italy', 'USA', 'Argentina', 'Portugal', 'Switzerland', 'Denmark', 'Mexico', 'Portugal', 'Norway', 'Sweden', 'Spain', 'France']

In [ ]:
# Generate synthetic data

users = {
    "customer_id": df_signup_dates['customer_id'],
    "signup_date": df_signup_dates['signup_date'],
    "country": np.random.choice(countries, n_customers),
    "age": np.random.randint(18, 80, n_customers)
}

In [ ]:
df_users = pd.DataFrame(users)

In [ ]:
df_users.head()

   customer_id signup_date   country  age
0            1  2025-04-01    Norway   61
1            2  2025-06-01    Norway   50
2            3  2025-02-01  Portugal   61
3            4  2025-01-01     Spain   36
4            5  2025-04-01   Germany   75

In [ ]:
df_users.shape

(100, 4)

In [ ]:
df_subscriptions.shape

(674, 4)

In [ ]:
# Save the DataFrame

df_users.to_csv('users_data.csv', index = False)